### ISSUE TITLE
branch creation

### ISSUE THREAD

**Issue by diaraand** [diaraand/GiTeam#1]

**Comment by diaraand** [comment]
done in https://github.com/gianlucacaiazza/swdevel-lab-hfarm/commit/7b806084fcbd28b3eaaa1e11fde299e2e50482b6

**Comment by annariso00** [comment]
done in https://github.com/gianlucacaiazza/swdevel-lab-hfarm/commit/8ae97cb6e9ab53227647761182015ebcfff52683

**Comment by chiarafornasa** [comment]
done in https://github.com/gianlucacaiazza/swdevel-lab-hfarm/commit/6d2ac37683fec692613a5170c6525cf2049f9b81

**Comment by ambra20** [comment]
done in https://github.com/diaraand/GiTeam/commit/ae4a2d517a6e394be1ef78c29ee8f07f79d7b19b

**Comment by jennyceapa** [comment]
done in 417701df1df1e8ea3a28c1742c67a74d7f5aab86
