### ISSUE TITLE
Second merge 

### ISSUE THREAD

**Issue by annariso00** [diaraand/GiTeam#28]

**Comment by annariso00** [comment]
done in ac3c536609d994d8aadbf1e8980c961bdedf18cf

**Comment by jennyceapa** [comment]
done in 449f49ac67d96324321129627b0a5c89471e1ee9

**Comment by chiarafornasa** [comment]
done in cd1f592d3291eef097beb93d9372deaf3592db14

**Comment by ambra20** [comment]
done in 29cff41845d9cc338ef5f2499db2d5e3182fcc48

**Comment by diaraand** [comment]
done in aa9d7f0ea2edfa3305eb75ef40cdc4fc5148da95
