### ISSUE TITLE
Merge our branches with master 

### ISSUE THREAD

**Issue by diaraand** [diaraand/GiTeam#3]

**Comment by annariso00** [comment]
done in https://github.com/gianlucacaiazza/swdevel-lab-hfarm/commit/d3c542be7ba0fb3901a1b6563f300a95e350cc8a

**Comment by chiarafornasa** [comment]
done in a611b3babc112e3ef7d9008c7f234ae64d304874

**Comment by diaraand** [comment]
done in https://github.com/gianlucacaiazza/swdevel-lab-hfarm/commit/34b9a15d55edf625126149a8ebba3e4bbe865eb6

**Comment by ambra20** [comment]
done in https://github.com/diaraand/GiTeam/commit/45effbbdc09c8cd3180a7794bc69b4d5be5ec471

**Comment by jennyceapa** [comment]
done in https://github.com/diaraand/GiTeam/commit/bda2ca64071727333eaefde779c40e76d025dd80
